# Generated by Django 5.0.3 on 2024-04-28 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('variant', models.JSONField(blank=True, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('purchased', 'Purchased'), ('removed', 'Removed')], default='active', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
